/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/todos": {
    /** retrieves all todos */
    get: {
      responses: {
        /** Ok */
        200: {
          content: {
            "application/json": components["schemas"]["Todo"][];
          };
        };
      };
    };
  };
  "/todo": {
    /** Retrieve a todo by id */
    get: {
      parameters: {
        query: {
          /** id of the todo you want to retrieve */
          id: string;
        };
      };
      responses: {
        /** Ok */
        200: {
          content: {
            "application/json": components["schemas"]["Todo"];
          };
        };
        /** Not found */
        404: {
          content: {
            "text/plain": unknown;
          };
        };
      };
    };
    /** updates an existing todo */
    put: {
      responses: {
        /** Ok */
        204: {
          content: {
            "text/plain": unknown;
          };
        };
        /** Validation Error */
        400: {
          content: {
            "text/plain": unknown;
          };
        };
        /** todo to update hasn't been found */
        404: {
          content: {
            "text/plain": unknown;
          };
        };
        /** Server Error */
        500: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateTodo"];
        };
      };
    };
    /** creates a new todo */
    post: {
      responses: {
        /** Ok */
        200: {
          content: {
            "application/json": string;
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["AddTodo"];
        };
      };
    };
    /** delete a todo */
    delete: {
      parameters: {
        query: {
          /** id of the todo to delete */
          id: string;
        };
      };
      responses: {
        /** Ok */
        200: {
          content: {
            "text/plain": unknown;
          };
        };
      };
    };
  };
  "/todoContent": {
    get: {
      parameters: {
        query: {
          /** id of the todo whose content you want to fetch */
          id: string;
        };
      };
      responses: {
        /** Ok */
        200: {
          content: {
            "text/plain": string;
          };
        };
        /** request validation error */
        400: {
          content: {
            "text/plain": string;
          };
        };
        /** Not found */
        404: {
          content: {
            "text/plain": unknown;
          };
        };
        /** server error */
        500: {
          content: {
            "text/plain": unknown;
          };
        };
      };
    };
  };
  "/todoCount": {
    get: {
      responses: {
        /** Ok */
        200: {
          content: {
            "text/plain": unknown;
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    Todo: {
      id: string;
      title: string;
      isDone: boolean;
    };
    AddTodo: {
      title: string;
      content?: string;
    };
    UpdateTodo: {
      id: string;
      title: string;
      content?: string;
      isDone: boolean;
    };
  };
}

export interface operations {}

export interface external {}
